[[language]]
name = "rust"
rulers = [101]

[language.config.check]
command = "clippy"
features = "all"

[language.config.rustfmt]
extraArgs = [ "+nightly" ]

[language.config.inlayHints]
bindingModeHints.enable = true
closingBraceHints.minLines = 1
closureReturnTypeHints.enable = "with_block"
discriminantHints.enable = "always"
lifetimeElisionHints.enable = "always"
typeHints.hideClosureInitialization = true
typeHints.enable = true
parameterHints.enable = true

[[language]]
name = "python"
rulers = [121]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
rulers = [121]
indent = { tab-width = 4, unit = "    " }
